insert into STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUE(101, 'SBI', 430.00);
insert into STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUE(102, 'BHEL', 43.00);
insert into STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUE(103, 'HDFC', 1440.00);
insert into STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUE(104, 'HCL', 950.00);
insert into STOCK_PRICE_DTLS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) VALUE(105, 'TCS', 2950.00);