server:
  port: 2222
  
  
spring:
  application:
    name: GREET-API
  
#If client server are in different machine then configure manually like below
#If this below URL is not given then it will search for defualt port 8761(eureka server)
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:9090}/eureka/
  